### ISSUE TITLE
CAGR

### ISSUE THREAD

**Issue by 19lex82** [ranaroussi/quantstats#1]
Hi, i use your module - thanks. i think the CAGR calculation is not correct. For example : 

```
                        Strategie          BM
Cumulative Return          81.23%      79.44%
CAGR%                      -1.38%      -1.52%
```
to check this quick, i used: 

 https://www.investopedia.com/calculator/cagr.aspx

Beginning Value:
100
Ending Value:
181.23
Number of Periods:
14

Result: Compound Annual Growth Rate:4.34%

greets

**Comment by ranaroussi** [comment]
When you say "periods" - what do you mean? days, months?

I've checked quantstats CAGR value to that of ``pyfolio`` and ``ffn`` and they all return the same value....

**Comment by 19lex82** [comment]
Hi Ran,

 

Periods are Years -also in the calculator from investopedia.

 

i calculated with daily Returns of S&P500 with quantstats:

 

                    Strategy
------------------  ----------
Start Period        1998-01-01
End Period          2019-01-01
Risk-free rate      0.0%
Exposure %          97.0%
Cumulative Return   283.41% >> correct!
CAGR%               4.85% 




The cum. Return is correkt. I think you calculate the CARG with a "Startvalue" of 100 and Endvalue of 283,41. The mistake is to use 283,41 as Endvalue. 

 

If i caclulate (Excel) an Start-Value with 100, i get 383,41 as Endvalue - this makes CAGR of 6,30%.

 

Another Example:

 



Performance Metrics




                           Strategy    Benchmark
-------------------------  ----------  -----------
Start Period               2005-01-03  2005-01-03
End Period                 2019-06-11  2019-06-11
Risk-free rate             0.0%        0.0%
Exposure %                 100.0%      100.0%
Cumulative Return          81.23%      79.44%
CAGR%                      -1.38%      -1.52%


 

 

Here we have a positive Cum.Return, but a negativ CAGR. if you assume 100 as Startvalue - indexed by the daily Returns you get 

181,23 Endvalue - CAGR of 4,34

 

greets lex

 

 




-----Ursprüngliche Nachricht-----
 Von: "Ran Aroussi" [notifications@github.com]
 Gesendet: Do. 13.06.2019 18:19
 An: "ranaroussi/quantstats" [quantstats@noreply.github.com]
 Kopie: "alex" [quantsummit@freenet.de],  "Author" [author@noreply.github.com]
 Betreff: Re: [ranaroussi/quantstats] CAGR (#1)





When you say "periods" - what do you mean? days, months?

I've checked quantstats CAGR value to that of pyfolio and ffn and they all return the same value....

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





-----Ursprüngliche Nachricht Ende-----

**Comment by ranaroussi** [comment]
Closing this for now as the CAGR calculation results in similar data to every stats library I've tested
