### ISSUE TITLE
html output

### ISSUE THREAD

**Issue by pbeng** [ranaroussi/quantstats#102]
I get the following output in Python console when running qs.reports.html(stock, "SPY"):

<IPython.core.display.HTML object>

How can I generate your statistics in an html file?

**Comment by damienklassen** [comment]
Need to put in an output location: 
qs.reports.html(stock, "SPY",output='test.html')

**Comment by pbeng** [comment]
Thanks a lot for your response. This was very helpful.

In general, this library has been a lifesaver.

**Comment by mrexito** [comment]
Once the html file has been created how can I open it in a Jupyter Notebook? thank you.

**Comment by Cokenach** [comment]
When I use:
`qs.reports.html(stock, "SPY", title='Strategy Tearsheet', download_filename='test.html',figfmt='svg', output=True)`
I see the html in terminal window, but it doesnt appear to get written as a file anywhere. There are no errors. Please can you advisor how I get html file written?
