### ISSUE TITLE
When rf is set to anything else than 0 : AttributeError: Can only use .dt accessor with datetimelike values

### ISSUE THREAD

**Issue by Harsh-Maheshwari** [ranaroussi/quantstats#103]
qs.reports.html(returns,'^NSEI', rf=0 ) : Works
Command: qs.reports.html(returns,'^NSEI', rf=0.1 ) : Doesn't Work

**AttributeError                            Traceback (most recent call last)**
<ipython-input-66-d09aa72fa604> in <module>
      8 returns = returns.droplevel('symbol')
      9 returns.index = pd.to_datetime(returns.index)
---> 10 qs.reports.html(returns,'^NSEI', rf=0.1 )

~/.local/lib/python3.8/site-packages/quantstats/reports.py in html(returns, benchmark, rf, grayscale, title, output, compounded, rolling_period, download_filename, figfmt, template_path)
     59     tpl = tpl.replace('{{v}}', __version__)
     60 
---> 61     mtrx = metrics(returns=returns, benchmark=benchmark,
     62                    rf=rf, display=False, mode='full',
     63                    sep=True, internal="True",

~/.local/lib/python3.8/site-packages/quantstats/reports.py in metrics(returns, benchmark, rf, display, mode, sep, compounded, **kwargs)
    307 
    308     # return df
--> 309     dd = _calc_dd(df, display=(display or "internal" in kwargs))
    310 
    311     metrics = _pd.DataFrame()

~/.local/lib/python3.8/site-packages/quantstats/reports.py in _calc_dd(df, display)
    581 def _calc_dd(df, display=True):
    582     dd = _stats.to_drawdown_series(df)
--> 583     dd_info = _stats.drawdown_details(dd)
    584 
    585     if dd_info.empty:

~/.local/lib/python3.8/site-packages/quantstats/stats.py in drawdown_details(drawdown)
    570         _dfs = {}
    571         for col in drawdown.columns:
--> 572             _dfs[col] = _drawdown_details(drawdown[col])
    573         return _pd.concat(_dfs, axis=1)
    574 

~/.local/lib/python3.8/site-packages/quantstats/stats.py in _drawdown_details(drawdown)
    563         df['start'] = df['start'].dt.strftime('%Y-%m-%d')
    564         df['end'] = df['end'].dt.strftime('%Y-%m-%d')
**--> 565         df['valley'] = df['valley'].dt.strftime('%Y-%m-%d')**
    566 
    567         return df

~/.local/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5454             or name in self._accessors
   5455         ):
-> 5456             return object.__getattribute__(self, name)
   5457         else:
   5458             if self._info_axis._can_hold_identifiers_and_holds_name(name):

~/.local/lib/python3.8/site-packages/pandas/core/accessor.py in __get__(self, obj, cls)
    178             # we're accessing the attribute of the class, i.e., Dataset.geo
    179             return self._accessor
--> 180         accessor_obj = self._accessor(obj)
    181         # Replace the property with the accessor object. Inspired by:
    182         # https://www.pydanny.com/cached-property.html

~/.local/lib/python3.8/site-packages/pandas/core/indexes/accessors.py in __new__(cls, data)
    492             return PeriodProperties(data, orig)
    493 
--> 494         **raise AttributeError("Can only use .dt accessor with datetimelike values")**

AttributeError: Can only use .dt accessor with datetimelike values

**Comment by wassname** [comment]
This happens to me when there are no drawdowns (often it's smoothly decreasing due to each trade being a loss). The results is df being an empty array with no index. So when

`df['valley'].dt.strftime('%Y-%m-%d')`

Is executed it gets an errors, because an empty index is not a datetimelike index.

**Comment by wassname** [comment]
It looks like this was due to the `prepare_returns` behaviour. So my solution was to set prepare_returns=False, and make sure I'm putting in returns as in pcnt_change rather than lettering the library auto detect and transform data into returns.
