### ISSUE TITLE
Plots Close Instantly in Terminal

### ISSUE THREAD

**Issue by rubikscube09** [ranaroussi/quantstats#107]
Hi! 

Big fan of these tearsheets - they are quite nice to look at and are quite useful. I was wondering if anyone else was having the issue of opening the plots generated in the (ipython) terminal - they are generated, but instantly closed afterwards. 

Thanks!

**Comment by justomarelli** [comment]
I have the same problem! Could you solve it? @rubikscube09

**Comment by rubikscube09** [comment]
@justomarelli unfortunately not! I just use the html reports now.

**Comment by a-m-p-m** [comment]
The same issue here.  python.org's IDLE, LiClipse - plot windows close immediately after opening.

**Comment by Shraneid** [comment]
@ranaroussi I had the same issue just now, running in pycharm and terminal was creating the same issue, I looked into the wrappers here https://github.com/ranaroussi/quantstats/blob/0a51fe05ebaa74b92d613d075cee2f02dd7fef31/quantstats/_plotting/wrappers.py#L166
I removed the block argument and it started working, the pyplot docs says it's doing it on default so not sure why we have to force it there (there might be a very good reason I don't know about, I just took 2 minutes to look into this and found out how to make it work)

so for anybody having the issue, just go to this file and change the line to `_plt.show()`
