### ISSUE TITLE
bug: qs.reports.html: TypeError

### ISSUE THREAD

**Issue by andreas-vester** [ranaroussi/quantstats#109]
Consider the following return series, which will be used as input for qs.reports.html:

2001-12-31: 0.0000
2002-01-02: 0.0000
2002-01-03: 0.0150
2002-01-04: -0.0020
...

In this specific case, I do get a ``TypeError: operands could not be broadcast together with shapes (258,), (259,)``. Unfortunately, I am not able to provide the concrete Traceback as I am working behind a corporate firewall (no copy&paste). However, the problem seems to be originated here:

https://github.com/ranaroussi/quantstats/blob/0f66023d421d864387c596f245244e0f324d7577/quantstats/reports.py#L131-L134

From what I can tell, this bug only appears when the very first entry of the return series is zero and from a different year compared to the second entry in the return series. However, this needs some more investigation on your side.

**Comment by KraxelHuber** [comment]
Can this bug be replicated on your side?
