### ISSUE TITLE
output

### ISSUE THREAD

**Issue by thepythonlab** [ranaroussi/quantstats#11]
hello everyone, how much I try to do :
qs.reports.html(returns=stock,benchmark=bench,output="report.html")

I get the following error:
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-15-897640eec3f8> in <module>
`----> 1 qs.reports.html(returns=stock,benchmark=bench,output='1.html')`

```
~\Miniconda3\envs\quant\lib\site-packages\quantstats\reports.py in html(returns, benchmark, rf, grayscale, title, output, compounded)
    205 
    206     with open(output, 'w') as f:
--> 207         f.write(tpl)
    208 
    209 

~\Miniconda3\envs\quant\lib\encodings\cp1252.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
     20 
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode character '\u2212' in position 649916: character maps to <undefined>

```
Any solution?
Thank you very much for your work!

**Comment by Whisperes** [comment]
In reports.py fix next line
`with open(file, 'w') as file:`
to
`with open(file, 'w', encoding='utf-8') as file:`

**Comment by ranaroussi** [comment]
Thanks! will do
