### ISSUE TITLE
Sharpe ratio based on monthly data backtesting

### ISSUE THREAD

**Issue by paulchoi77** [ranaroussi/quantstats#116]
Hi,
Calculated Sharpe ratio based on monthly data seems to be incorrect. It seems quite high. 
Backtesting based on daily data is correct though. Any chance to fix this problem?

Thanks!

**Comment by AntoineWSR** [comment]
Hello,
I have the same issue with Sharpe, Sortino and Volatility using weekly data. Is it meant to handle monthly or weekly data for those calculations?

Thanks

**Comment by BrandonStaab** [comment]
https://alo.mit.edu/wp-content/uploads/2017/06/The-Statistics-of-Sharpe-Ratios.pdf

**Comment by ranaroussi** [comment]
Have you tried passing `periods=12` to the `sharpe()` method?

**Comment by AntoineWSR** [comment]
Vol and Sharpe are getting much closer to expected by setting trading_year_days=52 for weekly.

**Comment by WoodWorker49** [comment]
> Vol and Sharpe are getting much closer to expected by setting trading_year_days=52 for weekly. Thanks @ranaroussi

HI @AntoineWSR, are you sure trading_year_days should be changed, knowing that the Sharpe Ratio should be annualized based on usually 252 days of trading per year?
