### ISSUE TITLE
Incompatible Version UnsatisfiableError on install

### ISSUE THREAD

**Issue by datatalking** [ranaroussi/quantstats#118]
Tried to install via `conda install -c ranaroussi quantstats` was hoping for a clean install but instead.

![Screen Shot 2021-09-01 at 9 07 08 AM](https://user-images.githubusercontent.com/11813209/131705640-e7fa1b45-5e07-4894-872e-f28dfe0d299e.png)

Is this a known issue or are there versions of MacOS that are known incompatible?

**Comment by hanrai** [comment]
`conda install -c ranaroussi quantstats
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions`

Same issue on Windows 10 PC

**Comment by dmicsa** [comment]
Same problem here. I had to use pip to install it.

**Comment by Karlheinzniebuhr** [comment]
Same issue,

```
conda install -c ranaroussi quantstats
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.|
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
