### ISSUE TITLE
[Suggestion] Add omega ratio.

### ISSUE THREAD

**Issue by cryptocoinserver** [ranaroussi/quantstats#123]
I was surprised the omega ratio isn't available.

It's easy to implement. I'm not that familiar with your code structure so you are probably faster adding it.

See here for a working implementation: 
[https://github.com/jesse-ai/crypto-empyrical/blob/master/crypto_empyrical/stats.py#L599](
https://github.com/jesse-ai/crypto-empyrical/blob/master/crypto_empyrical/stats.py#L599)

Thank you for this great library.

**Comment by ranaroussi** [comment]
Done :)

**Comment by cryptocoinserver** [comment]
Wow you are fast! Nice and thank you.
