### ISSUE TITLE
[Suggestion] The metrics are rounded by default. Make it optional?

### ISSUE THREAD

**Issue by cryptocoinserver** [ranaroussi/quantstats#124]
The metrics are rounded to 2 decimals by default. For some use-cases, it might be good to have the exact value and if needed do the rounding just if needed (for display for example). 

So it would be awesome to make it optional or at least add a parameter for the rounding precision. 

Thank you for this great library.

**Comment by timnilson** [comment]
What is the solution to getting non-rounded values when running qs.reports.metrics:

`metrics = qs.reports.metrics(returns, display=False, sep=False, mode="full"`

Values like "Max Drawdown" are rounded to -0.11, but in the HTML report the value is displayed as -10.9. 

Thank you for this great tool!!

**Comment by bastienjalbert** [comment]
> What is the solution to getting non-rounded values when running qs.reports.metrics:
> 
> `metrics = qs.reports.metrics(returns, display=False, sep=False, mode="full")`
> 
> Values like "Max Drawdown" are rounded to **-0.11,** but in the HTML report the value is displayed as **-10.9**.
> 
> Thank you for this great tool!!

I may not fully understand the exact solution (from your line of code) to get non-rounded values, but I used the same line, and I still get two decimals in the output (compared to the HTML report, which has more precision).
