### ISSUE TITLE
Saving the html

### ISSUE THREAD

**Issue by plajos1** [ranaroussi/quantstats#126]
Dear Ran, 
It is a great project. However I found that if you want to save the .html for later use

qs.reports.html(stock, benchmark="SPY", output=True, title=titlex, download_filename=tit_html,figfmt='svg')

 the system gives you "handle error". The cause is that in the reports.py in row 232 You have used the "output" for creating the file instead of the "download_filename":

with open(output, 'w', encoding='utf-8') as f:
with open(download_filename, 'w', encoding='utf-8') as f:

Louis Palanki

**Comment by yarimiz** [comment]
Created PR with a fix
https://github.com/ranaroussi/quantstats/pull/164
@ranaroussi please go over and approve if possible
