### ISSUE TITLE
Input - Manual Data frame or Data feed from Investpy 

### ISSUE THREAD

**Issue by nuwandwo** [ranaroussi/quantstats#131]
Dear Experts, 

Is it possible to put the data by manual excel or via investpy (investing.com feed) ?

I need to do analysis for stocks of Non - US

Thanks.

**Comment by gordongit2020** [comment]
I have the same need. I would like to import my historical log return using the common function:
df = pd.read_csv ('port_returns.csv' , index_col=0)  
I have this error: TypeError: unsupported operand type(s) for +: 'Timedelta' and 'str'
even if the serie generated by stock = qs.utils.download_returns('FB') seems similar to the serie imported. 
thx

G

**Comment by samithaj** [comment]
convert the date column to M8[ns] , then everything works as expected :)
`ev["date"]=ev["date"].astype("M8[ns]")`
