### ISSUE TITLE
Error when trying to collect Brazilian stock data

### ISSUE THREAD

**Issue by Prog-LucasAlves** [ranaroussi/quantstats#146]
I'm using the quantstats library to get the returns.

More presents the error below.

![Captura de tela 2021-11-09 132216](https://user-images.githubusercontent.com/68572723/140963663-a9e58ac0-e3a3-43d7-bbea-c7bddfb08674.png)

Obrigado.

**Comment by brubrant** [comment]
I think this is related to the dowloaded library.

A suggest you make sure you get yfinance lib working and then use quantstats

**Comment by Prog-LucasAlves** [comment]
ok
