### ISSUE TITLE
qs.reports.metrics returning none

### ISSUE THREAD

**Issue by bibinvargheset** [ranaroussi/quantstats#150]
p=qs.reports.metrics() shows the results but the the return value is blank DataFrame, how to get the report to Dataframe.  
Is it possible to compare more than two porfoliosin quantstats

**Comment by bibinvargheset** [comment]
Sorry, display=False solved the issue

**Comment by YifanD89** [comment]
> 

Can you elaborate? I am facing same issue.

**Comment by YifanD89** [comment]
Nvm, I get it.   qs.reports.metrics(df, mode="basic",display=False)
