### ISSUE TITLE
utils.make_index() doesn't function

### ISSUE THREAD

**Issue by mrexito** [ranaroussi/quantstats#153]
I have the following
![quantstat error](https://user-images.githubusercontent.com/51750327/145672475-7c9ac9bd-9664-4dbb-b9ba-fff73c1f7f95.png)

**Comment by msh855** [comment]
It works in my case. Check better what you did wrong

**Comment by TradingDominion** [comment]
Make sure that you don't have a local file in your current folder that you've named quantstats.py
