### ISSUE TITLE
Usings ETFs and streamlit platform, (also specifying specific time-series, etc endpoints)

### ISSUE THREAD

**Issue by abjfiner** [ranaroussi/quantstats#154]
Hi Ran,

Love your Quantstats package, its amazing, thanks for sharing it with he community

Theres a couple of issues that I would love to fix.

Im using Streamlit to publish the application, its easier to add a slider for time-series and ETF options. I see its not possible to add start and end points with Quanststats, so the specific points in investment history is not possible like 31/01/2021 - 30/06/2021. instead the default is today as the endpoint?

Secondly, when I add different ETFs, the returns seem to be same, which is probably my fault.

Ive attached screenshots below. Any advice, code solutions would be amazing.

Thank you Ran

<img width="1021" alt="Screenshot 2021-12-17 at 20 44 21" src="https://user-images.githubusercontent.com/40382338/146608865-fab87176-1c0e-44c7-9ede-13298288d9b1.png">
<img width="1015" alt="Screenshot 2021-12-17 at 20 44 37" src="https://user-images.githubusercontent.com/40382338/146608872-18b1ae08-bd11-4c1c-aa47-5e6d0a668515.png">
<img width="1015" alt="Screenshot 2021-12-17 at 20 45 01" src="https://user-images.githubusercontent.com/40382338/146608873-f01e27fd-915a-440c-a146-a6d8fb2222b7.png">
<img width="1007" alt="Screenshot 2021-12-17 at 20 45 41" src="https://user-images.githubusercontent.com/40382338/146608875-a66c38a4-2ee9-47e3-86fe-2511c6df9f33.png">
<img width="887" alt="Screenshot 2021-12-17 at 21 14 45" src="https://user-images.githubusercontent.com/40382338/146608877-bfbd52db-449e-4946-a765-d45bdf8ac8a8.png">

**Comment by nicktids** [comment]
to fix your problem you probably need to filter the dataframe and then run qs on the filtered data, or your not filtering correctly.

I have a question for you tho how did you get the stats to show up for the metrics in Streamlit.

I'm attempting to do the same as you but it is not working dataframe is not rendering correctly.

`matrix = qs.reports.metrics(port_ret_tidy,display=False)`
`st.markdown(matrix, unsafe_allow_html=True)`

**Comment by abjfiner** [comment]
Heya,

This guy fixed it, and you can clone his code for it.

https://www.youtube.com/watch?v=Dm8GaSYZPF8

https://github.com/hackingthemarkets/quantstats-demo

**Comment by Kvantly** [comment]
Hi
How do you get the output from Quantstats to be displayed in a streamlit app?
Help is appreciated
