### ISSUE TITLE
Error "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Prog-LucasAlves** [ranaroussi/quantstats#156]
Hello ,
I am using version 0.0.47 of QuantStats and python 3.9.5, and presents the following error when trying to collect the data from the assets.

![Captura de tela 2022-01-03 092725](https://user-images.githubusercontent.com/68572723/147930375-140900b0-d896-427d-809c-52a4fe857236.png)

**Comment by ranaroussi** [comment]
This is related to yfinance... You should install the latest yfinance version until I release an update to quantstats with an updated requirements file.

Upgrade yfinance using:
```pip install -U yfinance```

Let me know if that solved the problem for you
