### ISSUE TITLE
Payoff Ratio & Kelly Criterion

### ISSUE THREAD

**Issue by Juanignaciomarquez** [ranaroussi/quantstats#162]
Hi Ran. Thanks for sharing this amazing module.

I think that the index payoff ratio is showing the portfolio's ratio, and the Kelly Criterion is wrong due to that.

I hope that this comment can help to make Quantstats even better!

**Comment by ranaroussi** [comment]
Payoff ratio is calculated as avg. win / avg. loss... 
https://github.com/ranaroussi/quantstats/blob/b9073940c0f820699a02ec7cc19ab16566cc238a/quantstats/stats.py#L593
