### ISSUE TITLE
EOY Returns values doesn't match with graph

### ISSUE THREAD

**Issue by jdarias3** [ranaroussi/quantstats#172]
When runs an Html report, the data from the EOY Returns graph doesn't match with the Key Performance Metrics when benchmark is None

<img width="642" alt="image" src="https://user-images.githubusercontent.com/14876085/156900144-33e8987e-831e-4bff-8ff8-313a05f33668.png">

Year  |      Return            | Cumulative
----- | -----------------| --
2015 | 4088609.18%    | inf%
2016 | 7028080.04%    | inf%
2017 | 16818466.65%   | inf%
2018 | 43249527.67%   | inf%
2019 | 83941260.79%   | inf%
2020 | 112595171.44%  | inf%
2021 | 200606276.12% | inf%

**Comment by joaoppc** [comment]
It appears that the compunded is not passed through the EOY function on line 919 of the stats.py.

If you pass it it works.
