### ISSUE TITLE
v0.0.50, output parameter doesn't work.

### ISSUE THREAD

**Issue by qtbgo** [ranaroussi/quantstats#175]
In ver0.0.50, after executing qs.reports.html(myreturns, output='stats.html' ),  it generates quantstats-tearsheet.html instead of stats.html.

**Comment by rundef** [comment]
Try something like that: `qs.reports.html(returns, download_filename='myfile.html', output='yes')`

**Comment by adenhertog** [comment]
> Try something like that: `qs.reports.html(returns, download_filename='myfile.html', output='yes')`

This worked for me, thanks
