### ISSUE TITLE
when rf is not equal to zero, metric report doesn't look correct. 

### ISSUE THREAD

**Issue by sabirjana** [ranaroussi/quantstats#18]
qs.reports.full(stock,benchmark='^NSEI',rf=0.065)

Performance Metrics
                           Strategy    Benchmark
-------------------------  ----------  -----------

Start Period               2014-11-14  2014-11-14
End Period                 2019-11-14  2019-11-14
Risk-Free Rate             0.06%       0.06%
Time in Market             100.0%      100.0%

Cumulative Return          -100.0%     -100.0%
CAGR%                      -100.0%     -100.0%
Sharpe                     -62.45      -118.52
Sortino                    -15.39      -15.73

**Comment by sabirjana** [comment]
Hi,
I tried to look into it, seems following are the issues
1. utils._prepare_returns() invokes to_excess_returns every time wherever rf > 0 which is not right
2. to_excess_returns() is needed only in few cases such as in case of Sharpe, Sortino etc. and not in all cases when _prepare_returns() is called and rf>0

thank you

**Comment by sabirjana** [comment]
Hello Ran,
do you have any plan to update the master branch for this issue?
Thank
SJ

**Comment by brubrant** [comment]
This still happening: if RF is no 0 the reports are buggy...

**Comment by Zegoverno** [comment]
same here

**Comment by BartStolarek** [comment]
Still a bug?

**Comment by msh855** [comment]
You need to adjust the period. In my case it works. 

So, if you use monthly returns there is an argument in the function `periods_per_year`

for example, in this I am using monthly returns. So: 

qs.reports.full(portfolio, 'SPY', rf=0.02, periods_per_year=12)

![image](https://user-images.githubusercontent.com/26636184/153946410-9febbe2b-cd55-4e5b-b762-04512a02cd03.png)
