### ISSUE TITLE
Clarify max drawdowns by duration

### ISSUE THREAD

**Issue by okomarov** [ranaroussi/quantstats#19]
From: https://aroussi.com//assets/tearsheets/lazy.html

The drawdowns seem to be selected according to length, not depth. Can you confirm?

<img width="665" alt="Screenshot 2019-11-22 at 15 38 53" src="https://user-images.githubusercontent.com/3731173/69439312-99577300-0d3e-11ea-881c-1539ceaed001.png">

Maybe this should appear as a note under the plot.

**Comment by ranaroussi** [comment]
It says "periods" (length) :)

**Comment by okomarov** [comment]
It's still ambiguous as a Drawdown is a _period_ of decline. So, "Top 5 Drawdowns Periods" can be read as the 5 periods with the worst drawdowns.
On the other hand, "Top 5 Longest Drawdowns" makes it absolutely clear that the sort is on the duration of the drawdown and not on the severity.
