### ISSUE TITLE
Errors when there are no drawdowns

### ISSUE THREAD

**Issue by RatkoJ** [ranaroussi/quantstats#2]
Hello,

First of all, thank you very much for releasing this lib publicly. I've been using it since it's so much simpler to use than many other ones.

I did come across a problem when there aren't any drawdowns or if there are fewer than 5 drawdowns. The problem is in at least two places that I've seen.

In `stats._drawdown_details(drawdown)`, when returning `None` here, some code later expects a DataFrame and therefore it fails. 
```python
# no drawdown :)
if len(starts) == 0:
    return None
```

Even if above we return an empty DataFrame with the right column names, the code that uses this function still fails because `range(1,6)` is assigned to an index:
E.g. in `reports.full()`
```python
dd_info = _stats.drawdown_details(dd).sort_values(
        by='max drawdown', ascending=True)[:5]
dd_info.index = range(1, 6)   # <-- Fails here
```

**Comment by ranaroussi** [comment]
No drawdowns??! 😀 

Fixed in 0.0.16 ...

**Comment by RatkoJ** [comment]
Thank you for the quick fix.
It actually seems like there is one more obscure scenario. In `stats.drawdown_details()` we could have an ever-increasing series which means it starts with a drawdown but there is no `ends` so it fails with an IndexError. 
```python
# drawdown series begins in a drawdown
if starts[0] > ends[0]:  <-- ends could be empty
       starts.insert(0, drawdown.index[0])
```

I wish I had such strategies but in reality I am using your library to calculate incremental results as live trading goes on so in the beginning such scenarios can occur.

**Comment by ranaroussi** [comment]
Let me know if 0.0.17 fixed the issue

**Comment by athenawisdoms** [comment]
Getting the same error:

```
Traceback (most recent call last):
  File "test.py", line 269, in <module>
    qs.reports.html(returns['net_worth'], benchmark, output=os.path.join(projectDir, 'report.html'))
  File "/home/athena/anaconda3/envs/unicorn/lib/python3.8/site-packages/quantstats/reports.py", line 58, in html
    mtrx = metrics(returns=returns, benchmark=benchmark,
  File "/home/athena/anaconda3/envs/unicorn/lib/python3.8/site-packages/quantstats/reports.py", line 299, in metrics
    dd = _calc_dd(df, display=(display or "internal" in kwargs))
  File "/home/athena/anaconda3/envs/unicorn/lib/python3.8/site-packages/quantstats/reports.py", line 587, in _calc_dd
    'Longest DD Days': str(round(bench_dd.sort_values(
ValueError: cannot convert float NaN to integer
```

*Using quantstats 0.0.25, pandas 1.0.3*
