### ISSUE TITLE
The columns of "strategy" and "benchmark" are upside down.

### ISSUE THREAD

**Issue by jjaviergalvez** [ranaroussi/quantstats#20]
Hi Ran. Thanks for the library :)

The issue I'm reporting is that the columns in the tearsheet are not correct and need to be swapped.
For instance, in the following image, `Cumulative Return` and `Time in Market` is evidence that values don't correspond to the column.

![Screenshot from 2019-12-12 17-35-30](https://user-images.githubusercontent.com/24707368/70757682-1d7d9480-1d06-11ea-9c32-80af98f464f4.png)

Cheers!

**Comment by Sigmares** [comment]
Hi @ranaroussi . Thank you for this great library.

I realized the same issue than mentioned by @jjaviergalvez, I would even say that the tearsheet is mixing metrics from both columns.

`qs.reports.full(all_weather, "SPY")`
                           Strategy    Benchmark
-------------------------  ----------  -----------
Start Period               2006-02-07  2006-02-07
End Period                 2020-04-06  2020-04-06
Risk-Free Rate             0.0%        0.0%
Time in Market             100.0%      100.0%

Cumulative Return          176.18%     55.88%
CAGR%                      7.43%       3.18%
Sharpe                     0.46        0.33
Sortino                    0.64        0.45
Max Drawdown               -55.19%     -38.63%
Longest DD Days            1772        1310
Volatility (ann.)          11.62%      20.09%
R^2                        0.55        0.55
Calmar                     0.13        0.08
Skew                       -0.04       -0.38
Kurtosis                   16.38       7.38

Expected Daily %           0.04%       0.04%
Expected Monthly %         0.86%       0.86%
Expected Yearly %          10.22%      10.22%
Kelly Criterion            2.94%       -0.51%
Risk of Ruin               0.0%        0.0%
Daily Value-at-Risk        -1.19%      -2.05%
Expected Shortfall (cVaR)  -1.19%      -2.05%

Payoff Ratio               0.86        0.87
Profit Factor              1.1         1.06
Common Sense Ratio         0.97        1.03
CPC Index                  0.52        0.49
Tail Ratio                 0.88        0.97
Outlier Win Ratio          3.64        5.49
Outlier Loss Ratio         3.76        6.0

MTD                        1.59%       1.76%
3M                         -18.31%     -14.39%
6M                         -10.08%     -8.91%
YTD                        -18.17%     -13.44%
1Y                         -7.4%       -7.17%
3Y (ann.)                  5.74%       1.58%
5Y (ann.)                  6.98%       1.32%
10Y (ann.)                 10.42%      2.54%
All-time (ann.)            7.43%       3.18%

Best Day                   14.52%      6.27%
Worst Day                  -10.94%     -5.11%
Best Month                 10.92%      8.29%
Worst Month                -16.52%     -16.25%
Best Year                  32.31%      19.02%
Worst Year                 -36.79%     -18.84%

Avg. Drawdown              -1.74%      -2.52%
Avg. Drawdown Days         23          57
Recovery Factor            3.19        1.45
Ulcer Index                1.02        1.02

Avg. Up Month              3.36%       2.42%
Avg. Down Month            -4.29%      -3.22%
Win Days %                 55.2%       53.16%
Win Month %                67.25%      56.73%
Win Quarter %              74.14%      70.69%
Win Year %                 80.0%       66.67%

Beta                       0.43        -
Alpha                      -0.0        -

Kind regards!

**Comment by brunosafa** [comment]
@Sigmares @jjaviergalvez @ranaroussi 
How can I read data from a CSV file and use QuantStats with it? 

Thank you,
Bruno
