### ISSUE TITLE
utils.py:line94, .ix is deprecated resulting in FutureWarning

### ISSUE THREAD

**Issue by neilsmurphy** [ranaroussi/quantstats#21]
FutureWarning error in the utils.py module at line 94 in the rebase function. 

Pandas' .ix is now deprecated and a simple change to .iloc[0]  in the rebase function fixes this. I've run this in isolation and tested against both series and dataframe timeseries prices and it works well.

**Comment by ranaroussi** [comment]
Fixed in 0.0.24
