### ISSUE TITLE
Issue in conditional value at risk function in stats.py

### ISSUE THREAD

**Issue by HFTLabs** [ranaroussi/quantstats#22]
IndexError: invalid index to scalar variable. 
when doing cvar = returns[returns<var].mean()[0]

In conditional value at risk fn

**Comment by ranaroussi** [comment]
Please share more code :)

**Comment by HFTLabs** [comment]
Sorry for keeping it short ranaroussi. First of all, thank you for the wonderful work you're doing. Its of great help to me.
Now coming to the issue, in quantstats/stats.py file there is this function "conditional_value_at_risk" at line 369.
![image](https://user-images.githubusercontent.com/55708865/71443661-510ee480-2732-11ea-938f-49097f26d08a.png)
If I am calling that function with a pandas dataframe that has only one column (returns), it will throw the error "IndexError: invalid index to scalar variable." at line 376 "c_var = returns[returns < var].mean()[0]".
When there is only one column in pandas data frame, mean() returns a scalar and not a list. Hence trying to index will throw the error.
Whereas when calling the function with pandas dataframe containing more than one column, it works fine.

**Comment by ranaroussi** [comment]
Issue fixed in 0.0.25
