### ISSUE TITLE
Reports don't work for Python 3.10 because of datetime

### ISSUE THREAD

**Issue by EminentCoder** [ranaroussi/quantstats#222]
Hello all,
If I follow the tutorial on the readme, I run into the following issue:

Trying to use
`qs.reports.metrics(mode='basic|full", ...)`
`qs.reports.basic(...)`
`qs.reports.full(...)`
`qs.reports.html(...)`
doesn't work as there is apparently an issue with pandas.datetime and the regular python datetime:

> TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and datetime

My system runs on Ubuntu 22.04.1 LTS, uses python 3.10.6 and the following versions of the libraries:
- pandas (1.4.2)
- numpy (1.22.3)
- scipy (1.8.0)
- matplotlib (3.5.1)
- seaborn (0.12.0)
- tabulate (0.9.0)
- yfinance (0.1.77)
- plotly (5.10.0)

Maybe it would be best to use pd.datetime everywhere.
Kind regards!

PS: Also `stock = qs.utils.download_returns('FB')` should be replaced with a different stock, as FB changed its name and cannot be found in this way anymore.

**Comment by smooth-lee** [comment]
Hello. I think this problem is related to the time zone. So I solved it in the following way.

stock = qs.utils.download_returns("AAPL")

stock.index = stock.index.tz_convert(None) 

qs.reports.metrics(stock, mode="basic")

thx.

**Comment by YungAlfa** [comment]
I am having this issue also, particularly when trying to compare against a benchmark in html.

**Comment by jonnross88** [comment]
Hey,
I was able to compare against a benchmark by downloading the benchmark data and doing the same tz-naive trick described above.

stock = qs.utils.download_returns("META")
bench = qs.utils.download_returns("SPY")

stock.index = stock.index.tz_convert(None)
bench.index = bench.index.tz_convert(None)

qs.reports.html(stock, mode='full', benchmark=bench)

In case this helps.

Best,

**Comment by YungAlfa** [comment]
Thanks for this response. 

On top of this, do you know how to resolve this when making an index? I have tried;

portfolio.index = portfolio.index.tz_convert(None)

portfolio = qs.utils.make_index(tickers)

like above but it doesn't seem to work.

TIA.

**Comment by jonnross88** [comment]
I am not familiar with the function but are you trying to do something like this?
```
portfolio = qs.utils.make_index({"TSLA": 0.5, "META": 0.5})
portfolio.index = portfolio.index.tz_convert(None)
qs.reports.html(portfolio, benchmark=bench, mode="full")
```

**Comment by kins98** [comment]
Thanks for the help all - I was seeing the same issue too
