### ISSUE TITLE
TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and datetime

### ISSUE THREAD

**Issue by rokeds** [ranaroussi/quantstats#226]
This is my code:
```
import quantstats as qs

qs.extend_pandas()

stock = qs.utils.download_returns('GLD', period="10y")

qs.reports.html(stock, title='PTL Investments', output='output/gld.html')

qs.reports.html(stock, "SPY", title="GLD vs. SPY", output='output/gld_vs_spy.html')

stock = qs.utils.download_returns('QQQ', period="10y")

qs.reports.html(stock, "SPY", title="QQQ vs. SPY", output='output/qqq_ovs_spy.html')

stock = qs.utils.download_returns('TQQQ', period="10y")

qs.reports.html(stock, "QQQ", title="TQQQ vs. QQQ", output='output/tqqq_vs_qqq.html')

tickers = {
    'FB': 0.2,
    'AAPL': 0.2, 
    'AMZN': 0.2,
    'MSFT': 0.2,
    'GOOG': 0.2 
}

fmaga = portfolio = qs.utils.make_index(tickers)

qs.reports.html(fmaga, "qqq", output="output/fmaga_vs_qqq.html")`
```

and this is my output:

```
TypeError: Cannot compare tz-naive and tz-aware datetime-like objects

The above exception was the direct cause of the following exception:

InvalidComparison                         Traceback (most recent call last)
...
     33     typ = type(right).__name__
---> 34     raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
     35 return res_values

TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and datetime
```

**Comment by yenla9** [comment]
I have the same issue: 

InvalidComparison: 2022-11-01 00:00:00
During handling of the above exception, another exception occurred:
---> 34         raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
     35     return res_values
     36 
TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and datetime

**Comment by Pr4v33n23** [comment]
+1

**Comment by cameronqj** [comment]
+1

**Comment by mvolkening** [comment]
+1

**Comment by DiAlpin** [comment]
+1

**Comment by MidjoV** [comment]
+1

**Comment by bsakash137** [comment]
Any solution available for this yet, still facing the issue on this...

**Comment by yenla9** [comment]
There is a work around: 
SPY_qs = qs.utils.download_returns('SPY', period="6Y")
qs.reports.plots(SPY_qs, mode='full')

**Comment by bsakash137** [comment]
@yenla9 Thanks, I see benchmark comparison also works with individual plot reports... But is there a solution available with HTML tearsheet with benchmark comparison? Issue is coming when we have benchmark comparison with html report

**Comment by MidjoV** [comment]
Not sure if this is what you're after, but I download benchmark first, convert, and then add DataFrame to report
# adding benchmark
benchmark_SPY = pd.DataFrame(qs.utils.download_returns('SPY'))
benchmark_SPY.index = benchmark_SPY.index.tz_convert(None)
qs.reports.html(df, benchmark_SPY)

**Comment by rokeds** [comment]
yes, stock.index = stock.index.tz_convert(None) solved my problem, Thank you guys :)

**Comment by bsakash137** [comment]
> SPY_qs = qs.utils.download_returns('SPY', period="6Y")
> qs.reports.plots(SPY_qs, mode='full')

This worked Thanks alot, not sure why tz ocnversion is not built within...

**Comment by bsakash137** [comment]
@MidjoV, Thanks a lot your suggestion worked... not sure why tz conversion is not built within quantstats module...

**Comment by apachetrade** [comment]
I did the above but I am now experiencing an issue with the tearsheets:
_____
stock = qs.utils.download_returns("SPY")
bench = qs.utils.download_returns("SPY")

stock.index = stock.index.tz_convert(None)
bench.index = bench.index.tz_convert(None)

qs.reports.html(stock, bench)
______

when i run the above for the SAME underlying security(in this case the strategy and bench are both SPY) I do get a working plot but I do not get identical plots or identical output data...is anyone else experiencing this? They should be the same?

**Comment by drusakov778** [comment]
I have come across the same issue recently and it took me some time to dig into it. Here are my findings. quantstats version 0.0.55

the problem in my view arises from the fact that yfinance always returns non-naive with-timestamp data (in my case BTC-USD, tzinfo=UTC), this data is aligned with your returns and then, subsequently passed to reports.py, metrics() function, which computes different metrics, including monthly returns and so on, but then it creates naive datetime, which fail to compare with returns/benchmark df, see https://github.com/ranaroussi/quantstats/blob/main/quantstats/reports.py#L518

@wazimar fix, in https://github.com/ranaroussi/quantstats/pull/221 will probably fix it, but I believe it may require some edge case reviewing and treatment

I have solved it by manually downloading prices for the period of interest (I am passing actual portfolio values, quantstats seems to translate them nicely to returns by itself
```
def download_benchmark(self, benchmark: str, ind) -> pd.Series:
        """download benchmark data, for the (daily) indices given in 'ind'
        """
        # for last timestamp, require one day more, b/c otherwise since the timestamp is at 00:00
        # yfinance seems to actually filter last day
        first_ts = ind[0]
        last_ts = ind[-1] + dt.timedelta(days=1)
        benchmark_df = yfinance.Ticker(benchmark).history(interval='1d', start=first_ts, end=last_ts)

        # drop tz info, we assume it is UTC, we sanity check first index
        benchmark_df.index = pd.DatetimeIndex([d.replace(tzinfo=None) for d in benchmark_df.index])
        benchmark_pv = benchmark_df["Close"]

        # set correct benchmark name (instead of 'CLOSE')
        benchmark_pv.name = benchmark

        return benchmark_pv
```

subsequently it is passed to quantstats.reports.html(returns=pv, benchmark=benchmark_pv)
note that I am passing here actual portfolio values.

Passing returns also possible, but then previous day should also be pulled from yahoo, and also initial 0 returns added the day before, so that plots start at 0..

**Comment by KIC** [comment]
I have the same problem if my portfolio has a timezone-aware index, I can't get it to work even without using a benchmark.

**Comment by drusakov778** [comment]
> I have the same problem if my portfolio has a timezone-aware index, I can't get it to work even without using a benchmark.

yes, this is because internally metrics() function is always creating default naive (no tz) dates, see my analysis above

**Comment by jjphung** [comment]
Finally got it to work with:

```
import quantstats as qs
import pandas as pd
stock = pd.DataFrame(qs.utils.download_returns('AAPL'))
stock.index = stock.index.tz_convert(None) # make timezone agnostic.
stock = stock.squeeze() # back to a series
benchmark = pd.DataFrame(qs.utils.download_returns('MSFT'))
benchmark.index = benchmark.index.tz_convert(None) # make timezone agnostic.
qs.reports.html(stock, benchmark)
```

**Comment by jfitz001** [comment]
I did this and got it to work:
stock.index = pd.to_datetime(stock.index.strftime('%Y-%m-%d'))
