### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by paduel** [ranaroussi/quantstats#23]
After the last update of the code when importing quantstats it returns the error:

    AttributeError: 'str' object has no attribute 'magic

I checked the code and it's an error on line 278 of *utils.py*. Where it reads

    shell.magic("matplotlib inline")

should be

    get_ipython().magic("matplotlib inline").

You're doing a great job! Go for it!

**Comment by ranaroussi** [comment]
Thanks! Issue fixed in 0.0.25
