### ISSUE TITLE
qs.reports.html (Error)

### ISSUE THREAD

**Issue by Lauro-python** [ranaroussi/quantstats#232]
Hello, does anyone know why it doesn't work? or can you try another way?
![image](https://user-images.githubusercontent.com/119805924/205513314-61394a58-f200-436b-9a2f-679b9abcb8b9.png)

**Comment by victorncg** [comment]
I am having issues with "tz" too, seems it's related with datetime or time zones... still checking what's causing this

![image](https://user-images.githubusercontent.com/15315390/211647158-2d24e83c-6803-40f6-a609-4cdd333a8c4d.png)

**Comment by KIC** [comment]
This is really a nasty bug, currently, you have to remove the timezone in all date indices, meaning benchmark and portfolio.  A workaround is stated in this other issue https://github.com/ranaroussi/quantstats/issues/226

```python

benchmark = yf.Ticker("SPY").history(period='max')["Close"].pct_change().dropna()
benchmark.index = benchmark.index.tz_convert(None)

# do the same for the portfolio timeframe
portfolio.index = portfolio.index.tz_convert(None)

qs.reports.full(portfolio, benchmark)
```

This isn't very pleasant and quantstats should just make all indices timezone aware and 
 * use the timezones present
 * use the timezone of the other in case only one tz is None of benchmark and portfolio and log a warning
 * convert None timezone to UTC if only non-timezones were provided and log a warning

alternatively, remove all time zones and log a warning. However, there is a possibility that your portfolio holds European stocks while using s&p 500 as a benchmark.
