### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by Whisperes** [ranaroussi/quantstats#236]
As it said in readme:

> %matplotlib inline
> import quantstats as qs
> 
> qs.extend_pandas()
> 
> stock = qs.utils.download_returns('FB')
> 
> qs.stats.sharpe(stock)
> 
> stock.sharpe()

the execution result:

> Got error from yahoo api for ticker FB, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
> - FB: No timezone found, symbol may be delisted
> nan

**Comment by talaikis** [comment]
Submit a PR for `META` :-D
