### ISSUE TITLE
Error at package install - conda

### ISSUE THREAD

**Issue by QAdri25** [ranaroussi/quantstats#24]
Hi,

I'm trying to install QuantStats for Anaconda using this command: 
_"conda install -c ranaroussi quantstats"_

I am facing the following error:
"_The following NEW packages will be INSTALLED:

  multitasking       ranaroussi/noarch::multitasking-0.0.9-py_0
  quantstats         ranaroussi/noarch::quantstats-0.0.25-py_0
  tabulate           pkgs/main/win-64::tabulate-0.8.3-py37_0
  yfinance           ranaroussi/noarch::yfinance-0.1.54-py_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
yfinance-0.1.54      | 735 KB    | ############################################################################ | 100%

InvalidArchiveError('Error with archive C:\\Users\\mihae\\Anaconda3\\pkgs\\yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink (errno=22, retcode=-25, archive_p=1835644343904)')_
"
I've tried the suggested solution (delete and try again) but I haven't much success.

Could you please support me?

Thanks a lot,
Adriana

**Comment by Skullnick** [comment]
Same problem. Guess we need to use pip.

**Comment by dynoweb** [comment]
I originally installed yfinance-0.1.54-py_0 using pip.  When I tried installing quantStats, I was using conda.   I got the error above so I removed yfinance using pip, then tried again to install quantStats using conda with the same error as above.   Then I deleted the file and verified using conda list that yfinance wasn't installed and tried again with no luck.  Is there a problem with that package or am I doing something wrong?   Also, I noticed that yfinance-0.1.55 was the current version, can the QuantStats package get updated to include that latest version?

**Comment by Karlheinzniebuhr** [comment]
Same issue

```
conda install -c ranaroussi quantstats
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.|
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
