### ISSUE TITLE
html report file is empty

### ISSUE THREAD

**Issue by KIC** [ranaroussi/quantstats#243]
for some reason the html file for the report is empty:
```
qs.reports.html(dfhist["TOTAL", "return"], benchmark, output="assets/min-variance-report.html")
```
however the 
```
qs.reports.full(dfhist["TOTAL", "return"], benchmark)
```
works as expected.

No errors were thrown only several warnings about Arial font can't be found. 
> findfont: Font family 'Arial' not found.

**Comment by elektor123** [comment]
qs.reports.html takes pd.Series as input for strategy. Here you are giving a pandas as input.

Following code worked for me from backtrader timeReturn analyzer.

    returns_dict = thestrat.analyzers.time_return.get_analysis()
    # Convert the dictionary to a DataFrame
    returns_df = (
        pd.DataFrame(
            list(returns_dict.items()),
            columns = ["date", "return"]
        )
        .set_index("date")
    )
    returns = pd.Series(returns_df['return'])

**Comment by KIC** [comment]
I pass a series my frame has a MultiIndex and thus evaluates to a Series.
