### ISSUE TITLE
TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and datetime

### ISSUE THREAD

**Issue by fernfel** [ranaroussi/quantstats#245]
When running: qs.reports.html(stock, 'SPY')

I receive the following error message, any suggestions? (MacOS, Anaconda dist., Python 3.9.13)

ypeError                                 Traceback (most recent call last)
~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py in _validate_comparison_value(self, other)
    535             try:
--> 536                 self._check_compatible_with(other)
    537             except (TypeError, IncompatibleFrequency) as err:

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py in _check_compatible_with(self, other, setitem)
    507             return
--> 508         self._assert_tzawareness_compat(other)
    509         if setitem:

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py in _assert_tzawareness_compat(self, other)
    714         elif other_tz is None:
--> 715             raise TypeError(
    716                 "Cannot compare tz-naive and tz-aware datetime-like objects"

TypeError: Cannot compare tz-naive and tz-aware datetime-like objects

The above exception was the direct cause of the following exception:

InvalidComparison                         Traceback (most recent call last)
~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py in _cmp_method(self, other, op)
   1007         try:
-> 1008             other = self._validate_comparison_value(other)
   1009         except InvalidComparison:

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py in _validate_comparison_value(self, other)
    538                 # e.g. tzawareness mismatch
--> 539                 raise InvalidComparison(other) from err
    540 

InvalidComparison: 2023-01-01 00:00:00

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/var/folders/b1/q02cplr177s4vkwtr9grrc_00000gn/T/ipykernel_96916/4068622650.py in <module>
----> 1 qs.reports.html(stock, 'SPY')

~/opt/anaconda3/lib/python3.9/site-packages/quantstats/reports.py in html(returns, benchmark, rf, grayscale, title, output, compounded, periods_per_year, download_filename, figfmt, template_path, match_dates, **kwargs)
     94     tpl = tpl.replace('{{v}}', __version__)
     95 
---> 96     mtrx = metrics(returns=returns, benchmark=benchmark,
     97                    rf=rf, display=False, mode='full',
     98                    sep=True, internal="True",

~/opt/anaconda3/lib/python3.9/site-packages/quantstats/reports.py in metrics(returns, benchmark, rf, display, mode, sep, compounded, periods_per_year, prepare_returns, match_dates, **kwargs)
    516 
    517     today = df.index[-1]  # _dt.today()
--> 518     metrics['MTD %'] = comp_func(df[df.index >= _dt(today.year, today.month, 1)]) * pct
    519 
    520     d = today - relativedelta(months=3)

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/common.py in new_method(self, other)
     68         other = item_from_zerodim(other)
     69 
---> 70         return method(self, other)
     71 
     72     return new_method

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arraylike.py in __ge__(self, other)
     58     @unpack_zerodim_and_defer("__ge__")
     59     def __ge__(self, other):
---> 60         return self._cmp_method(other, operator.ge)
     61 
     62     # -------------------------------------------------------------

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py in _cmp_method(self, other, op)
   6700 
   6701         elif isinstance(self._values, ExtensionArray):
-> 6702             result = op(self._values, other)
   6703 
   6704         elif is_object_dtype(self.dtype) and not isinstance(self, ABCMultiIndex):

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/common.py in new_method(self, other)
     68         other = item_from_zerodim(other)
     69 
---> 70         return method(self, other)
     71 
     72     return new_method

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arraylike.py in __ge__(self, other)
     58     @unpack_zerodim_and_defer("__ge__")
     59     def __ge__(self, other):
---> 60         return self._cmp_method(other, operator.ge)
     61 
     62     # -------------------------------------------------------------

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py in _cmp_method(self, other, op)
   1008             other = self._validate_comparison_value(other)
   1009         except InvalidComparison:
-> 1010             return invalid_comparison(self, other, op)
   1011 
   1012         dtype = getattr(other, "dtype", None)

~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/invalid.py in invalid_comparison(left, right, op)
     32     else:
     33         typ = type(right).__name__
---> 34         raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
     35     return res_values
     36 

TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and datetime
​

**Comment by lorisnussbaumer** [comment]
I had a similar problem. Have a look at the csv files you are using. They should have the same format. After I changed the dateformat in excel and converted it back to .csv it worked. (not the nicest way i know, but it worked for me)

**Comment by DylanLoader** [comment]
I think this happens due to there being ambiguity in the timezone when the datetime object is converted to an index on data pulled from packages like yfinance. 

The way I fixed this was setting the index to UTC. 

cumulative_returns.index = cumulative_returns.index.tz_convert(None) # Sets the index timezone to UTC.

**Comment by amor71** [comment]
Had the same issue. The below fixed it for me:

`stock.index = pd.to_datetime(stock.index)`

**Comment by amor71** [comment]
Having the same issue, the above didn't resolve it for me

**Comment by scaratozzolo** [comment]
For me, I have a pandas Series of returns with a DatetimeIndex that has timezone info.  Removing the timezone info seems to have fixed it for me.


Before

Date
2022-01-28 00:00:00-05:00         NaN
2022-01-31 00:00:00-05:00    0.000000
2022-02-01 00:00:00-05:00    0.000000
2022-02-02 00:00:00-05:00    0.013758
2022-02-03 00:00:00-05:00   -0.021534
                               ...
2022-12-21 00:00:00-05:00    0.013243
2022-12-22 00:00:00-05:00   -0.039479
2022-12-23 00:00:00-05:00   -0.001873
2022-12-27 00:00:00-05:00   -0.042039
2022-12-28 00:00:00-05:00   -0.011638
Name: Portfolio_Value, Length: 231, dtype: float64

`returns.index = returns.index.tz_convert(None)`
After

Date
2022-01-28 05:00:00         NaN
2022-01-31 05:00:00    0.000000
2022-02-01 05:00:00    0.000000
2022-02-02 05:00:00    0.030630
2022-02-03 05:00:00   -0.025716
                         ...
2022-12-21 05:00:00    0.012014
2022-12-22 05:00:00   -0.033455
2022-12-23 05:00:00    0.003673
2022-12-27 05:00:00   -0.034238
2022-12-28 05:00:00   -0.014272

**Comment by ari62** [comment]
I needed to do:
```

returns.index = returns.index.tz_convert(None)
benchmark = pd.DataFrame(qs.utils.download_returns('SPY'))
benchmark.index = benchmark.index.tz_localize(None)
qs.reports.html(returns, benchmark=benchmark)
```
