### ISSUE TITLE
Monthly return heat chart cutting off

### ISSUE THREAD

**Issue by noobmaster29** [ranaroussi/quantstats#25]
I'm running the reports.plot with mode="full" and the top and bottom rows of the monthly returns chart is getting clipped (please see the attached screenshot). I was wondering if there is a way to add a bit of spacing on the top and bottom to get it to render properly. 

<img width="598" alt="Screen Shot 2020-02-07 at 1 55 47 AM" src="https://user-images.githubusercontent.com/39013477/74007773-22994180-494d-11ea-92b9-8ca47ba252ed.png">

Thanks for the help.

**Comment by cryptochuso** [comment]
Same issue.
