### ISSUE TITLE
Doubt regarding the kind of returns for input

### ISSUE THREAD

**Issue by vikaschouhan** [ranaroussi/quantstats#26]
First of all, I would like to thank for this really awesome tool. I have been trying to use it for some time and from the examples I see that almost all the functions need returns as input to generate the stats and tearsheet etc.
My doubt is that what kind of returns does this library assume. Is it simple returns calculated using pct_change() in pandas or log returns calculated using np.log(close_price).diff().

**Comment by AkiMosi** [comment]
Yes, by default it is like the pct_change() from pandas, but we can also tweak it to find log-returns using the qs.utils
