### ISSUE TITLE
How to save the report tearsheet as html in a local directory 

### ISSUE THREAD

**Issue by aayushah711** [ranaroussi/quantstats#27]
I am trying to run this code

> import quantstats as qs
> stock = qs.utils.download_returns('FB')
> qs.reports.html(stock, "SPY")
> 

the output I get on my spyder ide is:
_<IPython.core.display.HTML object>_

How do I save it as html in my pc?

**Comment by Illumaria** [comment]
Hello @aayushah711 , have you tried to specify the `output=` parameter?
Something like:
`qs.reports.html(stock, "SPY", output='/file-path/file-name.html')`

**Comment by aayushah711** [comment]
Yes that worked.. Thanks!

**Comment by Lauro-python** [comment]
Hello, does anyone know why it doesn't work? or can you try another way?

![image](https://user-images.githubusercontent.com/119805924/205513233-a6b634f3-c1e4-44c5-bcf1-af5f2c010a9f.png)
