### ISSUE TITLE
CAGR seems incorrect

### ISSUE THREAD

**Issue by kefa8** [ranaroussi/quantstats#3]
Hi,

Thanks for your library I'm using it. 

I was getting a negative CAGR when my total return was positive. There are 2 issues I think, firstly the year calculation does not cope with periods less than a year. Secondly in the total return part you need to add back 1.0 before you do the power calculation.

E.g. If I make 10% for 2 years then my total returns should be 21%. My CAGR should obviously be 10%. To achieve this calculation I need to compute (0.21 + 1.0) ** (1/2.0) - 1 

    # years = len(set(returns.index.year))
    years = (returns.index[-1] - returns.index[0]).days/365.0

    # res = abs(total / 1.0) ** (1.0 / years) - 1
    res = abs(total + 1.0) ** (1.0 / years) - 1

**Comment by ranaroussi** [comment]
Added to 0.0.17. Thanks!
