### ISSUE TITLE
Type Error on EOY Returns

### ISSUE THREAD

**Issue by rodrigolousada** [ranaroussi/quantstats#30]
Hi Ran,

I have been using quantstats to generate a complete report of my portfolio with the function **qs.reports.html** but it gave me a TypeError. After exploring the error a little bit more, if I use the function **qs.reports.full(trader.daily_returns, "SPY")** in a jupyter notebook it gives the Output until the **Cumulative Returns vs SPY (Volatility Matched)**. However while trying to print the graph **EOY Returns vs Benchmark**, the following error occurs:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-649f47ec8503> in <module>
----> 1 qs.reports.full(trader.daily_returns, "SPY")

~\Anaconda3\lib\site-packages\quantstats\reports.py in full(returns, benchmark, rf, grayscale, figsize, display, compounded)
    247 
    248     plots(returns=returns, benchmark=benchmark,
--> 249           grayscale=grayscale, figsize=figsize, mode='full')
    250 
    251 

~\Anaconda3\lib\site-packages\quantstats\reports.py in plots(returns, benchmark, grayscale, figsize, mode, compounded)
    509                           grayscale=grayscale,
    510                           figsize=(figsize[0], figsize[0]*.5),
--> 511                           show=True, ylabel=False)
    512 
    513     _plots.histogram(returns, grayscale=grayscale,

~\Anaconda3\lib\site-packages\quantstats\_plotting\wrappers.py in yearly_returns(returns, benchmark, fontname, grayscale, hlw, hlcolor, hllabel, match_volatility, log_scale, figsize, ylabel, subtitle, compounded, savefig, show)
    371                             grayscale=grayscale,
    372                             ylabel=ylabel,
--> 373                             subtitle=subtitle, savefig=savefig, show=show)
    374 
    375 

~\Anaconda3\lib\site-packages\quantstats\_plotting\core.py in plot_returns_bars(returns, benchmark, returns_label, hline, hlw, hlcolor, hllabel, resample, title, match_volatility, log_scale, figsize, grayscale, fontname, ylabel, subtitle, savefig, show)
    110     if benchmark is None:
    111         colors = colors[1:]
--> 112     df.plot(kind='bar', ax=ax, color=colors)
    113 
    114     fig.set_facecolor('white')

~\Anaconda3\lib\site-packages\pandas\plotting\_core.py in __call__(self, *args, **kwargs)
    792                     data.columns = label_name
    793 
--> 794         return plot_backend.plot(data, kind=kind, **kwargs)
    795 
    796     def line(self, x=None, y=None, **kwargs):

~\Anaconda3\lib\site-packages\pandas\plotting\_matplotlib\__init__.py in plot(data, kind, **kwargs)
     60             kwargs["ax"] = getattr(ax, "left_ax", ax)
     61     plot_obj = PLOT_CLASSES[kind](data, **kwargs)
---> 62     plot_obj.generate()
     63     plot_obj.draw()
     64     return plot_obj.result

~\Anaconda3\lib\site-packages\pandas\plotting\_matplotlib\core.py in generate(self)
    277     def generate(self):
    278         self._args_adjust()
--> 279         self._compute_plot_data()
    280         self._setup_subplots()
    281         self._make_plot()

~\Anaconda3\lib\site-packages\pandas\plotting\_matplotlib\core.py in _compute_plot_data(self)
    412         # no non-numeric frames or series allowed
    413         if is_empty:
--> 414             raise TypeError("no numeric data to plot")
    415 
    416         # GH25587: cast ExtensionArray of pandas (IntegerArray, etc.) to

TypeError: no numeric data to plot
```
![image](https://user-images.githubusercontent.com/24738828/76911043-9eb96a00-68a7-11ea-89c1-f5eebc38f702.png)

**Comment by Snowhit3** [comment]
I have managed to fix the issue by changing yearly_returns() in wrappers.py as follows:
`def yearly_returns(returns, benchmark=None,
                   fontname='Arial', grayscale=False,
                   hlw=1.5, hlcolor="red", hllabel="",
                   match_volatility=False,
                   log_scale=False, figsize=(10, 5), ylabel=True,
                   subtitle=True, compounded=True,
                   savefig=None, show=True):

    title = 'EOY Returns'
    if benchmark is not None:
        title += '  vs Benchmark'
        benchmark = _utils._prepare_benchmark(benchmark, 'max').resample('A').apply(_stats.compsum).resample('A').last()` 

This fixes the EOY returns plot, but the remaining charts are still missing the benchmark (only the strategy is shown). The only error I get is:
`/home/none/miniconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:2023: RuntimeWarning: invalid value encountered in multiply
  lower_bound = _a * scale + loc
/home/none/miniconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:2024: RuntimeWarning: invalid value encountered in multiply
  upper_bound = _b * scale + loc
/home/none/miniconda3/lib/python3.6/site-packages/quantstats/stats.py:633: RuntimeWarning: invalid value encountered in double_scalars
  beta = matrix[0, 1] / matrix[1, 1]
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
Report for /home/none/LeanResults/main.json generated`

**Comment by Snowhit3** [comment]
To fix the cumulative return charts I've edited _prepare_benchmark() in utils.py as follows:
```
def _prepare_benchmark(benchmark=None, period="max", rf=0.):
    """
    fetch benchmark if ticker is provided, and pass through
    _prepare_returns()

    period can be options or (expected) _pd.DatetimeIndex range
    """
    if benchmark is None:
        return None

    if isinstance(benchmark, str):
        benchmark = download_returns(benchmark)

    elif isinstance(benchmark, _pd.DataFrame):
        benchmark = benchmark[benchmark.columns[0]].copy()

    if isinstance(period, _pd.DatetimeIndex):
        benchmark = benchmark[~benchmark.index.duplicated()]
        condition = benchmark.index >= min(period)
        benchmark = benchmark[condition]

    return _prepare_returns(benchmark.dropna(), rf=rf)
```
