### ISSUE TITLE
Issues with running commands on Visual Studio

### ISSUE THREAD

**Issue by baqarjafri** [ranaroussi/quantstats#33]
Hi @ranaroussi ,
The static output works fine on visual studio but charts are not showing any output. 
1

`qs.plots.snapshot(df0['PPL_Return'],` title='PPL Performance')`

This command runs but no output is displayed. Is there any other command to add so that output can be displayed?

**Comment by glformanek** [comment]
Hi @ranaroussi, 

I too am having this same problem. I am running Python 3.9 in Visual Studio. This produces a quick flash like it is attempting to show a graph but then I see nothing. 
s = qs.utils.download_returns('AAPL')
qs.plots.snapshot(s, title='AAPL')

I've looked at the snapshot code but I can't see anything that might cause this.
Thanks!
