### ISSUE TITLE
Issue with qs.reports.html in Jupyter

### ISSUE THREAD

**Issue by RazHadas** [ranaroussi/quantstats#36]
Hi Ran,
I have an issue with "qs.reports.html". It works when I use "output=". But when I ran it on Jupyter notebook I don't get the output as you see in the screenshot. Do you know this issue with Jupyter?
I add another screenshot from inspect look like something  jquery erroer

Thank you in advance
![image](https://user-images.githubusercontent.com/65238333/87854033-65f1d600-c917-11ea-873d-fdeb051f027d.png)
![image](https://user-images.githubusercontent.com/65238333/87854210-fb419a00-c918-11ea-866b-f212c10be235.png)

**Comment by boyac** [comment]
@RazHadas I had the same issue with jupyter notebook earlier, you could tried 
```python
qs.reports.html(stock, "ticker", output="yourfilename.html")
```
