### ISSUE TITLE
Quantstats report to PDF

### ISSUE THREAD

**Issue by charlesedwards** [ranaroussi/quantstats#39]
Hi,

I'd like to create a nice PDF using Quantstats.

Is there a better way to do it other than:
- Run Python code to export as "HTML"
- Open HTML in Chrome
- Print as PDF

The problem is, a number of the charts get cut off and split across pages.

Please Let me know if there is a nice way to save and share these reports, ideally PDF!

Thank you,
CWSE

**Comment by charlesedwards** [comment]
found solution using pdfkit library

**Comment by jamesfulford** [comment]
Thank you @charlesedwards, that was a helpful suggestion to use pdfkit.

**Comment by richy1996** [comment]
> found solution using pdfkit library

Can you share an example using pdfkit?

**Comment by vincrichard** [comment]
Note for anyone wanting to do this, default parameter in `qs.reports.html` save the figure to SVG, which is not handle well with pdfkit. In my case, the figures were squished.
Using the following:

```python
qs.reports.html(
    data,
    benchmark=data,
    mode="full",
    output="report.html",
    figfmt="png",
)
pdfkit.from_file("report.html", "report.pdf")
```
Worked well, cheers
