### ISSUE TITLE
Error when final date is not today() and when number of drawdowns are less than 5

### ISSUE THREAD

**Issue by rubenyes** [ranaroussi/quantstats#4]
Hello,

First of all, thank you for your amazing library and work, is great!

I'm using it and I think I have discovered two little bugs:
1.- In reports.py line 71; `today = _dt.today()`
This line is good if the final date of the returns is equal to today(), but if we are doing a backtest, and the final date of teh returns where 2 years ago, this line is not correct. I think this can be solved changing that line to:
`today = df.index[-1]`

2.- In reports.py line 217; `dd_info.index = range(1, 6)`
The code breaks were there is less than 5 drawdowns. This can happen easily if our portfolio don't do to many operations. I think this can be fixed changing that line to:
`dd_info.index = range(1, min(6, len(dd_info)+1))`

3.- Finally, when I execute the some reports that include plots, I get the following error (executing the code from pycharm console):
```
...\lib\site-packages\quantstats\_plotting\wrappers.py:154: MatplotlibDeprecationWarning:

Passing the block parameter of show() positionally is deprecated since Matplotlib 3.1; the parameter will become keyword-only in 3.3.
```
I have tried to change every `_plt.show(fig) `to` _plt.show(fig, block=False) `and still not working, any idea of how can be solved that?

**Comment by ranaroussi** [comment]
items 1+2 fixed in the latest release. Thanks!

As for item 3 - after digging into `matplotlib`'s code - I really think this is a false positive. I used to see this deprecation warning and it drove me crazy, but after upgrading `matplotlib`- it was gone (at least on my machine).
