### ISSUE TITLE
Annualization Incorrect for Crypto

### ISSUE THREAD

**Issue by charlesedwards** [ranaroussi/quantstats#40]
Currently the stats.py annualizes using 252 period. There needs to be an option for 365 for crypto.

For running HTML reports, I can't see a straightforward way to annualise without overwritting the stats.py file.

Ideally this should be an input in reports.py.

Thanks

**Comment by ranaroussi** [comment]
0.0.33 added option to pass the number of days per year in reports, so you can now use ``trading_year_days=365`` if you're trading crypto, or any other number for intl. markets.
