### ISSUE TITLE
Question/Feature Request

### ISSUE THREAD

**Issue by cstampar** [ranaroussi/quantstats#41]
Hey thanks so much for your great work here! It is super useful. Would it be possible to pass your functions a list of Tickers and Weights so i can get a full report on a buy and hold portfolio over time? Thanks so much! :)

**Comment by fmilthaler** [comment]
Hi, sure. Here is a snippet of code that should do that for your portfolio `pf`:
```
# computing and plotting efficient frontier of pf
pf.ef_plot_efrontier()
# adding markers to optimal solutions
pf.ef_plot_optimal_portfolios()
# and adding the individual stocks to the plot
pf.plot_stocks()
plt.show()
```

**Comment by AnasEssahal** [comment]
> Hey thanks so much for your great work here! It is super useful. Would it be possible to pass your functions a list of Tickers and Weights so i can get a full report on a buy and hold portfolio over time? Thanks so much! :)

very good idea! Do we know when can this be delivered?
