### ISSUE TITLE
Help needed - adaption of Quantstats in order to do Backtest Analysis (Cryptotrading)

### ISSUE THREAD

**Issue by Prossi79** [ranaroussi/quantstats#43]
[backtest-result-2020-08-19_11-42-18.zip](https://github.com/ranaroussi/quantstats/files/5095868/backtest-result-2020-08-19_11-42-18.zip)

Thanks for this awesome open source project. I try to link it to another exciting project which is -> https://github.com/freqtrade/freqtrade

In Freqtrade you can do backtests with the strategy being crafted - however the analysis tools are currently limited. The backtest results are exported as .json files (example enclosed).

I have tried to "cast" the backtest results in the input format of Quantstats, which was working well to the point of plotting the snapshot. Here is my code - probably not the most elegant way (I am not a coder):

```
import quantstats as qs
from freqtrade.data.btanalysis import load_backtest_data

# extend pandas functionality with metrics, etc.
qs.extend_pandas()

# load backtest data
backtest = load_backtest_data('/home/andreas/freqtrade/user_data/backtest_results/backtest-result-2020-08-19_11-42-18.json') 

# define stake amount and compute equity curve
stake_amount = 100 
max_open_trades = 10
stake_amount_total = stake_amount * max_open_trades

backtest['profit_amount'] = (backtest['profit_percent']) * stake_amount  
backtest['cum_profit'] = backtest['profit_amount'].cumsum() # cumulated profits in stake currency
          
# prepare data for Quantstat format
backtest = backtest.set_index('close_date')
daily_resampled_data = backtest.cum_profit.resample('D').mean()
daily_resampled_data1 = daily_resampled_data.apply(lambda x: x + stake_amount_total) # add stake amount x max open trades

# feed own data into Quantstat "stock" algo
stock = daily_resampled_data1.pct_change()

# show performance plot
qs.plots.snapshot(stock, title='Performance')

```

When trying to apply the most interesting function (full report, benchmark e.g. LTC-USD) I got an error message:

`qs.reports.basic(stock, "LTC-USD")`

```
qs.reports.basic(stock, "LTC-USD")
<IPython.core.display.HTML object>
Traceback (most recent call last):

  File "<ipython-input-217-a1e5d119cf6e>", line 1, in <module>
    qs.reports.basic(stock, "LTC-USD")

  File "/home/andreas/anaconda3/lib/python3.7/site-packages/quantstats/reports.py", line 259, in basic
    compounded=compounded)

  File "/home/andreas/anaconda3/lib/python3.7/site-packages/quantstats/reports.py", line 299, in metrics
    dd = _calc_dd(df, display=(display or "internal" in kwargs))

  File "/home/andreas/anaconda3/lib/python3.7/site-packages/quantstats/reports.py", line 588, in _calc_dd
    by='days', ascending=False)['days'].values[0])),

ValueError: cannot convert float NaN to integer
```

What to do here?

**Comment by Corfucinas** [comment]
@Prossi79 

wrap it in Numpy using `nan_to_num`

[link](https://numpy.org/devdocs/reference/generated/numpy.nan_to_num.html)

I'm about to try this solution, to see if it works for me, but seeing your error message I think it's because you have an `unstable period` in `ta-lib`

**Comment by Corfucinas** [comment]
@ranaroussi 

Hey, I haven't spent to much time debugging the above or reading the entire code but found out that the `Nan` values are coming from `quantstats/reports.py` line 582

`bench_dd = dd_info['benchmark'].sort_values(by='max drawdown')` returns NaN with the above datasample.
I changed it to bench_dd = `dd_info['benchmark'].sort_values(by='max drawdown').fillna(0)`

Which will return

```
                                     returns benchmark
Max Drawdown %          -3.5542           0
Longest DD Days               14               0
Avg. Drawdown %         -0.928129        0
Avg. Drawdown Days              5            0
```

But in turn that creates another error at line 372
.
```
metrics['MTD %'] = comp_func(
        df[df.index >= _dt(today.year, today.month, 1)]) * pct```

`>>Cannot compare tz-naive and tz-aware datetime-like objects`

Not sure if you have come across this in the past
