### ISSUE TITLE
ErrorMessage

### ISSUE THREAD

**Issue by TomLoc** [ranaroussi/quantstats#5]
When I execute "qs.utils.download_returns('FB')" I get the following error message: AttributeError: module 'pandas.core.common' has no attribute '_dict_keys_to_ordered_list'.

The graphs and summary look really nice and powerful - thus it would be nice to use this library.

**Comment by ranaroussi** [comment]
This seems to be related to your problem:
https://stackoverflow.com/a/46483995/1783569

If the above solution isn't working, try running ``pip install pandas -U`` and let me know if it helped.

**Comment by TomLoc** [comment]
yes, that worked :-) simply restarting Spyder.
