### ISSUE TITLE
Unable to get Output in Jupyter for 'qs.reports.html'

### ISSUE THREAD

**Issue by SNabii** [ranaroussi/quantstats#52]
![Capture](https://user-images.githubusercontent.com/37283028/100905957-a630aa00-34ee-11eb-94b0-7dcc736844b2.PNG)

I am trying to  execute above code in Jupyter Notebook . unable to get the required output . Screen shot attached above in Image

**Comment by FriendlyUser** [comment]
I had a similar problem in google collab, I think you have to specific an output html file when using a jupyter notebook.

```
qs.reports.html(stock, "SPY", output="file.html")
```
