### ISSUE TITLE
Charts don't get displayed

### ISSUE THREAD

**Issue by brendler** [ranaroussi/quantstats#57]
Hello people, 
I'm trying to run the examples but for some reason the charts don't get displayed. It looks like the window flashes and closes itself straight after.
Has anyone else faced similar issue?
Thanks all

**Comment by qtbgo** [comment]
I have the same problem. If you use jupyter notebook, then it can display chart.

**Comment by limoon20** [comment]
Same problem. I do not use jupyter notebook. Any suggestion about displaying the plots using matplotlib?
Thanks

**Comment by limoon20** [comment]
Sorry, limoon again
This is what I meant in my previous request,

# Display figure in a Python environment
    plt.show()

Thanks
