### ISSUE TITLE
few of functionalities are not working for BTC price

### ISSUE THREAD

**Issue by anantaoutlook** [ranaroussi/quantstats#62]
Hi There,

thanks for creating such a wonderful library. Below 2 functionalities are not working for BTC prices. Is it known issue?

qs.reports.full(...)
qs.reports.html(...)

Please help!

Regards,
Ananta

**Comment by ranaroussi** [comment]
You can pass ``trading_year_days=365`` to these methods to have it calculate properly for cryptos 24/7/365 market
