### ISSUE TITLE
Error with Report.full output 

### ISSUE THREAD

**Issue by ariesvtb** [ranaroussi/quantstats#63]
TypeError                                 Traceback (most recent call last)
<ipython-input-13-3a502c461d07> in <module>()
      6 
      7 # (benchmark can be a pandas Series or ticker)
----> 8 qs.reports.full(stock_RoR)

3 frames
/usr/local/lib/python3.6/dist-packages/quantstats/reports.py in full(returns, benchmark, rf, grayscale, figsize, display, compounded)
    248 
    249     plots(returns=returns, benchmark=benchmark,
--> 250           grayscale=grayscale, figsize=figsize, mode='full')
    251 
    252 

/usr/local/lib/python3.6/dist-packages/quantstats/reports.py in plots(returns, benchmark, grayscale, figsize, mode, compounded, rolling_period)
    518                           grayscale=grayscale,
    519                           figsize=(figsize[0], figsize[0]*.5),
--> 520                           show=True, ylabel=False)
    521 
    522     _plots.histogram(returns, grayscale=grayscale,

/usr/local/lib/python3.6/dist-packages/quantstats/_plotting/wrappers.py in yearly_returns(returns, benchmark, fontname, grayscale, hlw, hlcolor, hllabel, match_volatility, log_scale, figsize, ylabel, subtitle, compounded, savefig, show)
    379                                   ylabel=ylabel,
    380                                   subtitle=subtitle,
--> 381                                   savefig=savefig, show=show)
    382     if not show:
    383         return fig

/usr/local/lib/python3.6/dist-packages/quantstats/_plotting/core.py in plot_returns_bars(returns, benchmark, returns_label, hline, hlw, hlcolor, hllabel, resample, title, match_volatility, log_scale, figsize, grayscale, fontname, ylabel, subtitle, savefig, show)
    109     if subtitle:
    110         ax.set_title("\n%s - %s                   " % (
--> 111             df.index.date[:1][0].strftime('%Y'),
    112             df.index.date[-1:][0].strftime('%Y')
    113         ), fontsize=12, color='gray')

**TypeError: 'method' object is not subscriptable**

**Comment by AnasEssahal** [comment]
I have the same issue. the Html report as well is broken. Is there any intermediary solution?
Thanks.

AE

**Comment by pchaganti** [comment]
Same issue. Anyone find a workaround?

**Comment by msaracer** [comment]
Same here

**Comment by lbonherbe** [comment]
I have the exact same issue as well

**Comment by shantanu-collab** [comment]
tried downgrading, still the same issue

![image](https://user-images.githubusercontent.com/56268734/122604744-17533b80-d094-11eb-98b2-23294a2217cb.png)
