### ISSUE TITLE
EOY chart Broken

### ISSUE THREAD

**Issue by duxiaoyao** [ranaroussi/quantstats#65]
In the function `yearly_returns` of _plotting/wrappers.py: benchmark index are timestamps, but returns is indexed in int-typed year.
```
    if benchmark is not None:
        title += '  vs Benchmark'
        benchmark = _utils._prepare_benchmark(
            benchmark, returns.index).resample('A').apply(
                _stats.compsum).resample('A').last()

    if compounded:
        returns = _utils.group_returns(returns, returns.index.year, True)
    else:
        returns = _utils.group_returns(returns, returns.index.year, False)
```

Then,

In the function `plot_returns_bars` of _plotting/core.py: df['Benchmark']  are NANs as benchmark.index.isin(returns.index) is always false, and df is empty after df.dropna()
```
    df = _pd.DataFrame(index=returns.index, data={returns_label: returns})
    if isinstance(benchmark, _pd.Series):
        df['Benchmark'] = benchmark[benchmark.index.isin(returns.index)]
        df = df[['Benchmark', returns_label]]

    df = df.dropna()
``` 

My current workaround: adds `benchmark.index = benchmark.index.year` in the function `yearly_returns`, and not sure if it is the right solution.

**Comment by forDaniel** [comment]
try to change your benchmark index type

benchmark.index = pd.to_datetime(benchmark.index, format='%Y-%m-%d')
