### ISSUE TITLE
Problem when daily return >= 100%

### ISSUE THREAD

**Issue by RatkoJ** [ranaroussi/quantstats#7]
Hi,

I've come across an edge case that took me quite a while to debug.
Basically when a daily return is >= 100% (during backtesting, pennystocks etc), `utils._prepare_prices()` thinks that the input series has already been converted to prices and it does nothing. This obviously messes up the calculations.

```python
elif data.min() <= 0 and data.max() < 1:
        data = to_prices(data, base)
```

For now as a hack I just clip all my returns to 0.9999.

Any thoughts on how to deal with this, given that it is an edge case... unfortunately :-)?
I think putting an `or`  instead of the `and` might be more robust, but still not foolproof.

**Comment by ranaroussi** [comment]
Fixed in 0.0.21
