### ISSUE TITLE
Creating reports on monthly returns data

### ISSUE THREAD

**Issue by lndkcg** [ranaroussi/quantstats#74]
When creating a report, all of the stats+metrics are called from the base functions using default arguments. The default period argument is 252 (representing daily returns data). So if you pass monthly returns to the report call, you will get incorrect values for stats like volatility, sharpe, or anything that needs to be annualized.

Can we add a `period` as an optional parameter to the reports functions, and then pass that to the underlying functions which require it?

**Comment by ranaroussi** [comment]
Fixed in 0.0.34
