### ISSUE TITLE
No output for html reports

### ISSUE THREAD

**Issue by boyac** [ranaroussi/quantstats#76]
Hi team, I have tried to run reports functions on jupyter notebook. However, there's no outpute for
 qs.reports.html(stock, "SPY"), could any one advise what's missing? Thanks
`
- qs.reports.metrics(mode='basic|full", ...) - shows basic/full metrics
- qs.reports.plots(mode='basic|full", ...) - shows basic/full plots
- qs.reports.basic(...) - shows basic metrics and plots
- qs.reports.full(...) - shows full metrics and plots
- qs.reports.html(...) - generates a complete report as html`

**Comment by boyac** [comment]
problem solved

**Comment by AkiMosi** [comment]
No output is generated for me too, How did you solve this problem? @boyac

**Comment by boyac** [comment]
@AkiMosi Please try this out qs.reports.html(output="yourfilename.html")

**Comment by AkiMosi** [comment]
Yaa, got the file. Thank you @boyac

**Comment by boyac** [comment]
@AkiMosi awesome! 👍
