### ISSUE TITLE
Unable to generate all the graphs and stats with qs.reports.full()

### ISSUE THREAD

**Issue by stanleyy123** [ranaroussi/quantstats#79]
I'm having trouble getting the part of the charts and table with qs.reports.full(). I was able to get everything up until the Distubtion of Monthly Returns graph. Below are my codes and the error... 
Any clue?

qs.reports.full(df["Model Return"], benchmark=df["Benchmark Return"])

--
TypeError                                 Traceback (most recent call last)
<ipython-input-43-ba1fda74054c> in <module>()

----> 5 qs.reports.full(df["Model Return"], benchmark=df["Benchmark Return"])

3 frames
/usr/local/lib/python3.7/dist-packages/quantstats/_plotting/core.py in plot_histogram(returns, resample, bins, fontname, grayscale, title, kde, figsize, ylabel, subtitle, compounded, savefig, show)
    348         lambda x, loc: "{:,}%".format(int(x*100))))
    349 
--> 350     ax.axhline(0.01, lw=1, color="#000000", zorder=2)
    351     ax.axvline(0, lw=1, color="#000000", zorder=2)
    352 

TypeError: 'method' object is not subscriptable

**Comment by petersandersen** [comment]
Getting the same issue here, whether I use custom data from my own models or the facebook example in the quick-start section. Oddly enough qs.reports.html(stock, "SPY") works fine but qs.reports.full(stock, "SPY") does not.

Thanks for the awesome package by the way, its just what I've been looking for. Planning to setup a pipeline that runs a notebook with our latest data then pushes it to hugo for static site generation thats always up to date with our (test stage) funds results.
