### ISSUE TITLE
problem to visualize heatmap

### ISSUE THREAD

**Issue by giulianoyunes** [ranaroussi/quantstats#8]
Hi there Ran! 
First of all, thanks for this piece of art you've made. It's been working great for my needs. I really appreciate the correlation heatmap provided, but after some time using it I got a visualization problem, having the edge boxes cut in half. Any ideas for fixing that? 
<img width="1012" alt="Captura de Tela 2019-09-19 às 19 28 42" src="https://user-images.githubusercontent.com/54076147/65288136-c0fa4700-db13-11e9-85b5-ee5659029fd7.png">

**Comment by ranaroussi** [comment]
From: https://github.com/mwaskom/seaborn/issues/1773#issuecomment-509362057

This was a ``matplotlib`` regression introduced in 3.1.1 which has been fixed in 3.1.2 (still forthcoming). For now the fix is to downgrade matplotlib to a prior version.
