### ISSUE TITLE
Proposal: Positions analysis

### ISSUE THREAD

**Issue by mgrytsai** [ranaroussi/quantstats#83]
It would be great to expand the existing tearsheet functionality with position analysis and include such metrics: long/short positions over time, leverage, portfolio allocation. Something similar exists in Pyfolio

**Comment by datatalking** [comment]
@mike565 provide a reference link to that in Pyfolio, could we use their reporting and bring the two together some how?

**Comment by ranaroussi** [comment]
@mike565 - This would require you to provide trade information to QuantStats, whereas (currently, at least) it is relying on returns only.
