### ISSUE TITLE
plot_histogram broken starting in 0.0.27

### ISSUE THREAD

**Issue by JugglingNumbers** [ranaroussi/quantstats#94]
Starting with 0.0.27 calling

`qs.reports.full(finalRets.mean(axis=1).loc['2000-01-01':], benchmark.loc['2000-01-01':])`

results in:
![image](https://user-images.githubusercontent.com/51210436/116792494-f193b800-aa8e-11eb-902c-23ba95aa1e28.png)

This was caused by changing to using _utils.group_returns() starting in line 326 for the grouping which produces a multi-index (year, month) instead of keeping the dateTime index. 0.0.25 has apply_fn at line 315 and works:
![image](https://user-images.githubusercontent.com/51210436/116792500-f8222f80-aa8e-11eb-9bc8-b0e175870190.png)

I've tested this on Ubuntu 18.04 python 3.7 with both pandas 0.28 and 1.1.5 and on windows 10 python 3.8 with pandas 1.1.5 with the same results.

**Comment by ranaroussi** [comment]
Fixed in 0.0.32 - thanks for pipointing this
